

service: nodeless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:getObject
        - s3:putObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: servelessdeploygui
    events:
      - s3:
          bucket: servelessdeploygui
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: servelessdeploygui
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploads/
            - suffix: .png